# -----------------------------
# 1. Import Libraries and Generate Moons Dataset
# -----------------------------
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_moons

# Generate a synthetic two-moons dataset with 100 samples, 0.15 noise, and a fixed random state
x, y = make_moons(n_samples=100, noise=0.15, random_state=1)

# Inspect the shapes and first few entries
print("Feature shape:", x.shape)
print("Target shape:", y.shape)
print("First 3 rows of features:\n", x[:3])

# -----------------------------
# Polynomial Feature Expansion with LinearSVC Pipeline
# -----------------------------
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.svm import LinearSVC

# Construct a pipeline combining polynomial features (degree 3), scaling, and LinearSVC
poly_svm_clf = Pipeline([
    ('poly_features', PolynomialFeatures(degree=3, include_bias=False)),
    ('scaler', StandardScaler()),
    ('svm_clf', LinearSVC(max_iter=10000, C=10, loss='hinge', random_state=1))
])

# Fit the pipeline to the dataset (x, y from make_moons)
poly_svm_clf.fit(x, y)

# Inspect the intercept and coefficients of the underlying LinearSVC model
print("Intercept:", poly_svm_clf['svm_clf'].intercept_)
print("Coefficients:\n", poly_svm_clf['svm_clf'].coef_)

# Get feature names generated by PolynomialFeatures
# Note: In newer scikit-learn versions, use get_feature_names_out(['x1', 'x2']) instead of get_feature_names
print("Feature Names:", poly_svm_clf['poly_features'].get_feature_names_out(['x1', 'x2']))

# Evaluate accuracy score on the dataset
print("Score:", poly_svm_clf.score(x, y))

def plot_predictions(model, axes=[-1.5, 2.5, -1, 1.5]):
    # 1. Create a dense grid based on the specified axis boundaries [xmin, xmax, ymin, ymax]
    x1s = np.linspace(axes[0], axes[1], 1000)
    x2s = np.linspace(axes[2], axes[3], 1000)
    x1, x2 = np.meshgrid(x1s, x2s)
    X_new = np.c_[x1.ravel(), x2.ravel()]

    # 2. Predict class labels across the grid and plot filled classification regions
    y_pred = model.predict(X_new).reshape(x1.shape)
    plt.contourf(x1, x2, y_pred, cmap=plt.cm.brg, alpha=0.2)

    # 3. Compute decision function confidence scores and plot boundary/margin lines at levels [-1, 0, 1]
    y_decision = model.decision_function(X_new).reshape(x1.shape)
    plt.contour(x1, x2, y_decision, colors='k', levels=[-1, 0, 1], linestyles=['--', '-', '--'], alpha=0.8)

    # 4. Plot actual training data points for class 0 (blue circles) and class 1 (red triangles)
    plt.plot(x[y == 0, 0], x[y == 0, 1], 'bo', markersize=3, label='$y=0$')
    plt.plot(x[y == 1, 0], x[y == 1, 1], 'r^', markersize=3, label='$y=1$')
    
    # 5. Configure legend placement and axis labels
    plt.legend(loc='upper right')
    plt.xlabel('$x_1$', fontsize=18)
    plt.ylabel('$x_2$', fontsize=18)

    # Set the figure size to 5 inches wide by 3 inches high
plt.figure(figsize=(5, 3))

# Call the custom plot_predictions function using our trained polynomial SVM pipeline
plot_predictions(poly_svm_clf)

# Render and display the plot
plt.show()

# -----------------------------
# Polynomial Feature Expansion with SGDClassifier Pipeline
# -----------------------------
from sklearn.linear_model import SGDClassifier

# Construct a pipeline combining polynomial features (degree 3), scaling, 
# and SGDClassifier configured with hinge loss, L2 penalty, and alpha=0.001
sgd_clf = Pipeline([
    ('poly_features', PolynomialFeatures(degree=3, include_bias=False)),
    ('scaler', StandardScaler()),
    ('sgd', SGDClassifier(loss='hinge', penalty='l2', alpha=0.001, random_state=1))
])

# Fit the pipeline to the dataset (x, y from make_moons)
sgd_clf.fit(x, y)

# Inspect the intercept and coefficients of the underlying SGD classifier model
print("Intercept:", sgd_clf['sgd'].intercept_)
print("Coefficients:\n", sgd_clf['sgd'].coef_)

# Evaluate accuracy score on the dataset
print("Score:", sgd_clf.score(x, y))

# Set the figure size to 5 inches wide by 3 inches high
plt.figure(figsize=(5, 3))

# Call the custom plot_predictions function using our trained SGDClassifier pipeline
plot_predictions(sgd_clf)

# Render and display the plot
plt.show()

# -----------------------------
# Polynomial Kernel SVM Classification Pipeline
# -----------------------------
from sklearn.svm import SVC
import matplotlib.pyplot as plt

# Construct a pipeline combining feature scaling and an SVC model with a polynomial kernel
poly_clf = Pipeline([
    ('scaler', StandardScaler()),
    ('poly_svc', SVC(kernel='poly', degree=3, coef0=1, C=10, random_state=1))
])

# Fit the pipeline to the dataset (x, y from make_moons)
poly_clf.fit(x, y)

# Evaluate accuracy score on the dataset
print("Score:", poly_clf.score(x, y))


# -----------------------------
# Visualizing Polynomial Kernel SVM Predictions
# -----------------------------
# Set the figure size to 5 inches wide by 3 inches high
plt.figure(figsize=(5, 3))

# Call the custom plot_predictions function using our trained polynomial kernel SVM pipeline
plot_predictions(poly_clf)

# Render and display the plot
plt.show()


# -----------------------------
# RBF Kernel SVM Classification Pipeline
# -----------------------------
from sklearn.svm import SVC
import matplotlib.pyplot as plt

# Construct a pipeline combining feature scaling and an SVC model with a Radial Basis Function (RBF) kernel
rbf_clf = Pipeline([
    ('scaler', StandardScaler()),
    ('linear_svc', SVC(kernel='rbf', gamma=5, C=10, random_state=1))
])

# Fit the pipeline to the dataset (x, y from make_moons)
rbf_clf.fit(x, y)

# Evaluate accuracy score on the dataset
print("Score:", rbf_clf.score(x, y))


# -----------------------------
# Visualizing RBF Kernel SVM Predictions
# -----------------------------
# Set the figure size to 5 inches wide by 3 inches high
plt.figure(figsize=(5, 3))

# Call the custom plot_predictions function using our trained RBF kernel SVM pipeline
plot_predictions(rbf_clf)

# Render and display the plot
plt.show()